In [1]:
import os
import numpy as np

In [4]:
user_id = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
num_data_list = [277, 174, 369, 437, 361, 426, 405, 249, 484, 324, 430, 441, 365, 323, 414, 474, 471, 485, 330, 390, 242, 297]
num_data_dict = {}

for i, user in enumerate(user_id):
    num_data_dict[user] = num_data_list[i]

In [3]:
model_list = sorted(os.listdir('wgt'))
print (model_list)

['LSTM_USER_10_c11_lr1e-05_wd0.01_dr0.4', 'LSTM_USER_10_c11_lr1e-05_wd0.01_dr0.4_bi', 'LSTM_USER_10_c11_lr1e-05_wd0.01_dr0.4_bi_s15', 'LSTM_USER_11_c11_lr1e-05_wd0.01_dr0.4', 'LSTM_USER_11_c11_lr1e-05_wd0.01_dr0.4_bi', 'LSTM_USER_11_c11_lr1e-05_wd0.01_dr0.4_bi_s15', 'LSTM_USER_12_c13_lr1e-05_wd0.01_dr0.4', 'LSTM_USER_12_c13_lr1e-05_wd0.01_dr0.4_bi', 'LSTM_USER_12_c13_lr1e-05_wd0.01_dr0.4_bi_s15', 'LSTM_USER_1_c15_lr1e-05_wd0.01_dr0.4', 'LSTM_USER_1_c15_lr1e-05_wd0.01_dr0.4_bi', 'LSTM_USER_1_c15_lr1e-05_wd0.01_dr0.4_bi_s15', 'LSTM_USER_21_c13_lr1e-05_wd0.01_dr0.4', 'LSTM_USER_21_c13_lr1e-05_wd0.01_dr0.4_bi', 'LSTM_USER_21_c13_lr1e-05_wd0.01_dr0.4_bi_s15', 'LSTM_USER_22_c12_lr1e-05_wd0.01_dr0.4', 'LSTM_USER_22_c12_lr1e-05_wd0.01_dr0.4_bi', 'LSTM_USER_22_c12_lr1e-05_wd0.01_dr0.4_bi_s15', 'LSTM_USER_23_c13_lr1e-05_wd0.01_dr0.4', 'LSTM_USER_23_c13_lr1e-05_wd0.01_dr0.4_bi', 'LSTM_USER_23_c13_lr1e-05_wd0.01_dr0.4_bi_s15', 'LSTM_USER_24_c15_lr1e-05_wd0.01_dr0.4', 'LSTM_USER_24_c15_lr1e-05_wd0.

In [5]:
## transformer
setting = 'dh16_dm16_he4_l3_lr1e-05_wd0.01_dr0.4_nosche_s10_es41_fin_mep300'

accu_dict = {}
num_label_dict = {}
for model in model_list:
    if setting in model:
        userid = model.split('_')[1]
        nclass = model.split('_')[2][1:]
        best_accu = np.load('./wgt/'+model+'/best_accu.npy')
        accu_dict[userid] = best_accu
        print (model, userid, best_accu)
        num_label_dict[userid] = nclass

USER_10_c11_dh16_dm16_he4_l3_lr1e-05_wd0.01_dr0.4_nosche_s10_es41_fin_mep300 10 [50.         85.41666667 96.875      30.20833333]
USER_11_c11_dh16_dm16_he4_l3_lr1e-05_wd0.01_dr0.4_nosche_s10_es41_fin_mep300 11 [32.82442748 68.70229008 89.3129771  38.16793893]
USER_12_c13_dh16_dm16_he4_l3_lr1e-05_wd0.01_dr0.4_nosche_s10_es41_fin_mep300 12 [49.62962963 77.77777778 91.11111111 37.03703704]
USER_1_c15_dh16_dm16_he4_l3_lr1e-05_wd0.01_dr0.4_nosche_s10_es41_fin_mep300 1 [28.39506173 49.38271605 62.96296296 41.97530864]
USER_21_c13_dh16_dm16_he4_l3_lr1e-05_wd0.01_dr0.4_nosche_s10_es41_fin_mep300 21 [34.54545455 66.36363636 75.45454545 23.63636364]
USER_22_c12_dh16_dm16_he4_l3_lr1e-05_wd0.01_dr0.4_nosche_s10_es41_fin_mep300 22 [41.66666667 66.66666667 81.25       34.375     ]
USER_23_c13_dh16_dm16_he4_l3_lr1e-05_wd0.01_dr0.4_nosche_s10_es41_fin_mep300 23 [45.23809524 79.36507937 89.68253968 19.04761905]
USER_24_c15_dh16_dm16_he4_l3_lr1e-05_wd0.01_dr0.4_nosche_s10_es41_fin_mep300 24 [28.08219178

In [5]:
## LSTM
mname = 'LSTM'
setting = '_lr1e-05_wd0.01_dr0.4'

accu_dict = {}
num_label_dict = {}
for model in model_list:
    if mname in model:
        if setting in model:
            if 'bi' not in model:
                userid = model.split('_')[2]
                nclass = model.split('_')[3][1:]
                best_accu = np.load('./wgt/'+model+'/best_accu.npy')
                accu_dict[userid] = best_accu
                print (model, userid, best_accu)
                num_label_dict[userid] = nclass

LSTM_USER_10_c11_lr1e-05_wd0.01_dr0.4 10 [37.5        75.         93.26923077 21.15384615]
LSTM_USER_11_c11_lr1e-05_wd0.01_dr0.4 11 [22.30215827 58.27338129 84.17266187 69.78417266]
LSTM_USER_12_c13_lr1e-05_wd0.01_dr0.4 12 [33.09859155 69.71830986 89.43661972 28.16901408]
LSTM_USER_1_c15_lr1e-05_wd0.01_dr0.4 1 [31.81818182 53.40909091 60.22727273  1.13636364]
LSTM_USER_21_c13_lr1e-05_wd0.01_dr0.4 21 [18.8034188  46.15384615 71.79487179 30.76923077]
LSTM_USER_22_c12_lr1e-05_wd0.01_dr0.4 22 [25.24271845 51.45631068 74.75728155 40.77669903]
LSTM_USER_23_c13_lr1e-05_wd0.01_dr0.4 23 [24.81203008 52.63157895 75.18796992  3.7593985 ]
LSTM_USER_24_c15_lr1e-05_wd0.01_dr0.4 24 [24.83660131 49.01960784 75.16339869 27.45098039]
LSTM_USER_25_c13_lr1e-05_wd0.01_dr0.4 25 [27.63157895 65.13157895 79.60526316 34.86842105]
LSTM_USER_26_c14_lr1e-05_wd0.01_dr0.4 26 [24.84076433 63.05732484 76.43312102 28.02547771]
LSTM_USER_27_c12_lr1e-05_wd0.01_dr0.4 27 [26.41509434 49.05660377 65.09433962 43.39622642]
L

In [6]:
## biLSTM
mname = 'LSTM'
setting = '_lr1e-05_wd0.01_dr0.4_bi'

accu_dict = {}
num_label_dict = {}
for model in model_list:
    if mname in model:
        if setting in model:
            if 's15' not in model:
                userid = model.split('_')[2]
                nclass = model.split('_')[3][1:]
                best_accu = np.load('./wgt/'+model+'/best_accu.npy')
                accu_dict[userid] = best_accu
                print (model, userid, best_accu)
                num_label_dict[userid] = nclass

LSTM_USER_10_c11_lr1e-05_wd0.01_dr0.4_bi 10 [44.11764706 80.39215686 96.07843137 26.47058824]
LSTM_USER_11_c11_lr1e-05_wd0.01_dr0.4_bi 11 [37.22627737 79.5620438  91.24087591 82.48175182]
LSTM_USER_12_c13_lr1e-05_wd0.01_dr0.4_bi 12 [43.97163121 84.39716312 92.90780142 44.68085106]
LSTM_USER_1_c15_lr1e-05_wd0.01_dr0.4_bi 1 [32.18390805 57.47126437 68.96551724 45.97701149]
LSTM_USER_21_c13_lr1e-05_wd0.01_dr0.4_bi 21 [30.17241379 70.68965517 82.75862069 33.62068966]
LSTM_USER_22_c12_lr1e-05_wd0.01_dr0.4_bi 22 [40.19607843 72.54901961 87.25490196 36.2745098 ]
LSTM_USER_23_c13_lr1e-05_wd0.01_dr0.4_bi 23 [40.15151515 71.96969697 86.36363636 46.21212121]
LSTM_USER_24_c15_lr1e-05_wd0.01_dr0.4_bi 24 [34.86842105 57.89473684 76.31578947 38.15789474]
LSTM_USER_25_c13_lr1e-05_wd0.01_dr0.4_bi 25 [28.47682119 64.90066225 79.47019868 42.38410596]
LSTM_USER_26_c14_lr1e-05_wd0.01_dr0.4_bi 26 [41.93548387 70.32258065 85.80645161 21.29032258]
LSTM_USER_27_c12_lr1e-05_wd0.01_dr0.4_bi 27 [27.88461538 48.07

In [7]:
## MLP
mname = 'MLP'
setting = '_lr1e-05_wd0.01_dr0.4'

accu_dict = {}
num_label_dict = {}
for model in model_list:
    if mname in model:
        userid = model.split('_')[2]
        nclass = model.split('_')[3][1:]
        best_accu = np.load('./wgt/'+model+'/best_accu.npy')
        accu_dict[userid] = best_accu
        print (model, userid, best_accu)
        num_label_dict[userid] = nclass

MLP_USER_10_c11_lr1e-05_wd0.01_dr0.4 10 [48.11320755 77.35849057 94.33962264 24.52830189]
MLP_USER_11_c11_lr1e-05_wd0.01_dr0.4 11 [30.4964539  72.34042553 90.78014184 79.43262411]
MLP_USER_12_c13_lr1e-05_wd0.01_dr0.4 12 [40.68965517 75.17241379 89.65517241 31.03448276]
MLP_USER_1_c15_lr1e-05_wd0.01_dr0.4 1 [30.76923077 51.64835165 67.03296703 36.26373626]
MLP_USER_21_c13_lr1e-05_wd0.01_dr0.4 21 [21.66666667 48.33333333 66.66666667 39.16666667]
MLP_USER_22_c12_lr1e-05_wd0.01_dr0.4 22 [33.96226415 61.32075472 78.30188679 33.96226415]
MLP_USER_23_c13_lr1e-05_wd0.01_dr0.4 23 [30.14705882 39.70588235 49.26470588  0.73529412]
MLP_USER_24_c15_lr1e-05_wd0.01_dr0.4 24 [25.         51.92307692 73.07692308 24.35897436]
MLP_USER_25_c13_lr1e-05_wd0.01_dr0.4 25 [40.64516129 68.38709677 80.         35.48387097]
MLP_USER_26_c14_lr1e-05_wd0.01_dr0.4 26 [38.75  70.625 80.625 21.25 ]
MLP_USER_27_c12_lr1e-05_wd0.01_dr0.4 27 [28.7037037  49.07407407 63.88888889  8.33333333]
MLP_USER_28_c12_lr1e-05_wd0.01_d

In [8]:
## ensemble

accu_dict = {}
id_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
for id in id_list:
    best_accu = np.load('./ensemble/USER_%s_best_accu.npy'%(id))
    accu_dict[str(id)] = best_accu
    print (id, best_accu)

1 [31.03448276 59.77011494 70.11494253]
2 [32.0754717  50.94339623 66.03773585]
3 [33.33333333 65.81196581 82.05128205]
4 [43.88489209 76.25899281 92.8057554 ]
5 [53.50877193 79.8245614  88.59649123]
6 [41.17647059 73.52941176 91.17647059]
7 [29.45736434 62.01550388 78.29457364]
8 [40.25974026 61.03896104 68.83116883]
9 [34.19354839 63.87096774 80.        ]
10 [56.8627451  83.33333333 96.07843137]
11 [37.95620438 78.83211679 91.24087591]
12 [51.77304965 83.68794326 95.74468085]
21 [35.34482759 67.24137931 76.72413793]
22 [46.07843137 72.54901961 80.39215686]
23 [43.18181818 79.54545455 86.36363636]
24 [30.26315789 59.86842105 73.02631579]
25 [43.70860927 68.21192053 80.79470199]
26 [43.87096774 70.96774194 82.58064516]
27 [30.76923077 53.84615385 74.03846154]
28 [45.96774194 73.38709677 89.51612903]
29 [52. 92. 96.]
30 [61.29032258 84.94623656 93.5483871 ]


In [9]:
resstr = ''
for uid in user_id:
    resstr += '%.2f & '%(accu_dict[str(uid)][0])
print (resstr)

31.03 & 32.08 & 33.33 & 43.88 & 53.51 & 41.18 & 29.46 & 40.26 & 34.19 & 56.86 & 37.96 & 51.77 & 35.34 & 46.08 & 43.18 & 30.26 & 43.71 & 43.87 & 30.77 & 45.97 & 52.00 & 61.29 & 


In [5]:
for i, key in enumerate(accu_dict):
    print (key, accu_dict[key], num_data_dict[int(key)], num_label_dict[key])

NameError: name 'num_label_dict' is not defined

In [13]:
## random
resstr = ''
rand_sum = 0
for num_label in num_label_dict:
    rand_sum += (1/int(num_label_dict[num_label])*100)
    resstr += '%.2f & '%(1/int(num_label_dict[num_label])*100)

print (resstr)
rand_top1 = rand_sum/len(num_label_dict)
rand_top3 = rand_top1*3
rand_top5 = rand_top1*5
rand_emo_top1 = 1/7

print (rand_top1, rand_top3, rand_top5, rand_emo_top1)

9.09 & 9.09 & 7.69 & 6.67 & 7.69 & 8.33 & 7.69 & 6.67 & 7.69 & 7.14 & 8.33 & 8.33 & 8.33 & 10.00 & 11.11 & 7.69 & 9.09 & 9.09 & 8.33 & 9.09 & 6.25 & 6.67 & 
8.185759947123584 24.55727984137075 40.92879973561792 0.14285714285714285


In [6]:
accu_list = np.array(list(accu_dict.values()))

In [7]:
accu_list

array([[31.03448276, 59.77011494, 70.11494253],
       [32.0754717 , 50.94339623, 66.03773585],
       [33.33333333, 65.81196581, 82.05128205],
       [43.88489209, 76.25899281, 92.8057554 ],
       [53.50877193, 79.8245614 , 88.59649123],
       [41.17647059, 73.52941176, 91.17647059],
       [29.45736434, 62.01550388, 78.29457364],
       [40.25974026, 61.03896104, 68.83116883],
       [34.19354839, 63.87096774, 80.        ],
       [56.8627451 , 83.33333333, 96.07843137],
       [37.95620438, 78.83211679, 91.24087591],
       [51.77304965, 83.68794326, 95.74468085],
       [35.34482759, 67.24137931, 76.72413793],
       [46.07843137, 72.54901961, 80.39215686],
       [43.18181818, 79.54545455, 86.36363636],
       [30.26315789, 59.86842105, 73.02631579],
       [43.70860927, 68.21192053, 80.79470199],
       [43.87096774, 70.96774194, 82.58064516],
       [30.76923077, 53.84615385, 74.03846154],
       [45.96774194, 73.38709677, 89.51612903],
       [52.        , 92.        , 96.   

In [8]:
assert len(accu_list) == 22
print (np.mean(accu_list, axis=0), np.std(accu_list, axis=0))

# act: top-1, top-3, top-5 accuracy, emo: top-1 accuracy

# transformer (max epoch: 300): 
# [40.62454987 69.02194153 82.38714842 33.97171654]
# [ 9.57108627 10.62929207  8.96274048 11.29893385]

# transformer (max epoch: 200): 
# [39.18143241 68.80929301 82.09137429 33.65331358]
# [ 9.49634242 11.3510773   9.31828819  8.08337773]

## bugged version.
# mean: [26.62238106 55.61127428 76.45854408 28.56130491]
# std: [5.11078506 8.2678025  9.37273395 8.8938811 ]

# lstm
# mean: [25.92302486 56.48506932 77.33377992 31.50305819]
# std: [ 6.06328515 10.63867412 10.34317686 17.17978742]

# mlp
# mean: [33.26056753 62.0178878  78.01481917 33.33849482] 
# std: [ 8.47313367 12.72439321 11.25052287 16.95875482]

# lstm (bidirectional)
# mean: [35.51997566 67.77329351 83.60966744 42.99564205]
# std: [ 8.32280296 12.92765809  9.27393565 13.71449994]

# ensemble (mlp, bilstm, transformer)
# [41.7268719  70.97639514 83.36168091]
# [ 9.05395226 10.50779085  9.15628724]

# ensemble (lstm, bilstm, mlp)
# mean: [34.83324271 67.46487105 81.59658155]
# std: [ 8.55675731 11.31451984  9.08870279]

[41.7268719  70.97639514 83.36168091] [ 9.05395226 10.50779085  9.15628724]


In [10]:
user_id = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
import numpy as np

emo_losses_list = []
for uid in user_id:
    fname = 'ensemble/USER_%s_emo_losses.npy'%(uid)
    emo_losses = np.load(fname)
    emo_losses_list.append(emo_losses)
    
assert len(emo_losses_list) == 22
print (np.mean(emo_losses_list, axis=0), np.std(emo_losses_list, axis=0)) # mlp, lstm, bilstm

[0.0223908  0.0248678  0.01304572 0.01520205] [0.03606879 0.03118572 0.00773412 0.00858365]
